food/apps/blog/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="blog_app"
urlpatterns = [
    path('add-key-word/', add_key_word, name="add_key_word"),
    path('delete-key-word/<int:id>/', add_key_word, name="delete_key_word"),
    path('edit-key-word/<int:id>/', edit_key_word, name="edit_key_word"),
    path('show-key-word/<int:id>/', show_key_word, name="show_key_word"),
    path('show-key-words/', show_key_words, name="show_key_words"),
    
    path('add-blog/', add_article, name="add_blog"),
    path('delete-blog/<str:slug>/', add_article, name="delete_blog"),
    path('edit-blog/<str:slug>/', edit_article, name="edit_blog"),
    path('show-blog/<str:slug>/', show_article, name="show_blog"),
    path('<int:id>/', show_article_with_id, name="show_article_with_id"),
    path('show-blogs/', show_all_article, name="show_blogs"),
    path('show-blogs-with-author//<str:author_slug>/', show_article_with_author, name="show_article_with_author"),
    
    path('add-author/', add_author, name="add_author"),
    path('delete-author/<str:slug>/', add_author, name="delete_author"),
    path('edit-author/<str:slug>/', edit_author, name="edit_author"),
    path('show-author/<str:slug>/', show_author, name="show_author"),
    path('show-authors/', show_all_author, name="show_authors"),
    
    
    path('add-like/', add_like, name="add_like"),
    path('add-dislike/', add_dislike, name="add_dislike"),
]

food/apps/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="food_app"
urlpatterns = [ 
    # path('add-food/', add_food,name="add_food"),
    # path('delete-food/<int:id>/', delete_food,name="delete"),
    # path('edit-food/<int:id>/', edit_food,name="edit_food"),
    path('show-food/<str:slug>/',show_food,name="show_food"),
    path('show-food-part/',show_food_info,name="show_food_info"),
    path('show-foods/group/<str:group_id>/',show_foods_g,name="show_foods_width_group"),
    path('show-foods/',show_foods,name="show_foods"),
    path('show-similar-foods/',show_similar_foods,name="show_similar_foods"),
    
    path('add-to-my-recipes/',add_to_my_recipes,name="add_to_my_recipes"),
    path('update-my-recipe/',update_my_recipe,name="update_my_recipe"),
    path('delete-my-recipe/',delete_my_recipe,name="delete_my_recipe"),
    path('show-my-recipes/',show_my_recipes,name="show_my_recipes"),
    path('show-my-recipe/<int:recipe_id>/',show_my_recipe,name="show_my_recipe"),
    
    path('add-food-group/', add_food_group,name="add_food_group"),
    path('delete-food-group/', delete_food_group,name="delete_food_group"),
    path('edit-food-group/', edit_food_group,name="edit_food_group"),
    path('show-food-groups/',show_food_groups,name="show_food_groups"),
    
    path('add-recipes/',add_recipes,name="add_recipes"),
    path('delete-recipes/<int:id>/',delete_recipes,name="delete_recipes"),
    path('edit-recipes/',edit_recipes,name="edit_recipes"),
    path('show-recipe/<str:slug>/',show_recipes,name="show_recipe"),
    path('recipe/<int:id>/',show_recipe_with_id,name="show_recipe_with_id"),
    path('show-recipes/',show_all_recipes,name="show_recipes"),
    path('add-like-recipe/',add_like_recipe,name="add_like_recipe"),
    path('add-dislike-recipe/',add_dislike_recipe,name="add_dislike_recipe"),
    
    path('what',what_food,name="what_food"),
    
    path('show-comments/',show_comments,name="show_comments"),
]

food/apps/gift/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="gift_app"
urlpatterns = [ 
    path('show-wheel-of-luck/', show_wheel_of_luck,name="show_wheel_of_luck"),
    path('get-gift-in-wheel-of-luck/', get_gift_in_wheel_of_luck,name="get_gift_in_wheel_of_luck"),
    path('show-lotteries/', show_lotteries,name="show_lotteries"),
    path('wins-lottery/', wins_lottery,name="wins_lottery"),
]

food/apps/main/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name='main_app'
urlpatterns = [
    path('', index,name='index'),
    path('about-me/', about_me,name='about_me'),
    path('rules/', rules,name='rules'),
    path('show-frequently-asked-questions/', show_frequently_asked_questions,name='show_frequently_asked_questions'),
    path('download/<str:content_type>/<str:file_path>/', download,name='download'),
    path('save-image/', save_image,name='save_image'),   
]

# handler404 = 'apps.main.views.http_status_404'

food/apps/message/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name = "message_app"
urlpatterns = [
    path('contact-us/', add_message, name='contact_us'),
    path('show-box/', show_box, name='show_box'),
    path('start-chat-online/', add_user_in_chat_room, name='start_online_chat'),
    path('show-messages/', show_messages, name='show_messages'),
    path('refresh-messages/', refresh_messages, name='refresh_messages'),
    
    path('add-message/', add_message_online_chat, name='send_message'),
    path('show-chat/', show_chat_room, name='show_chat'),
    path('clear-chat/', clear_chat, name='clear_chat'),
    path('manage-chat-room/', manage_chat_room, name='manage_chat_room'),
    path('manage-chat-room/show-messages/', show_messages_in_manage_chat_room, name='show_messages_in_manage_chat_room'),
]

food/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""food URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path('scores/', include("apps.scores.urls",namespace="scores_app")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

urlpatterns+=i18n_patterns(
    path('', include("apps.message.urls",namespace="message_app")),
    path('favorites/', include("apps.favorites.urls",namespace="favorites_app")),
    path('my-environment/', include("apps.my_environment.urls",namespace="my_environment_app")),
    path('data-manager/', include("apps.data_manager.urls",namespace="data_manager_app")),
    path('event/', include("apps.event.urls",namespace="event_app")),
    path('language/', include("apps.language.urls",namespace="language_app")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('', include("apps.main.urls",namespace="main_app")),
    path('food/', include("apps.food.urls",namespace="food_app"),name="food_app"),
    path('blog/', include("apps.blog.urls",namespace="blog_app"),name="blog_app"),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('orders/', include("apps.orders.urls",namespace="orders_app")),
    path('accounts/', include("apps.accounts.urls",namespace="accounts_app")),
    path('search/', include("apps.search.urls",namespace="search_app")),
    path('discounts/', include("apps.discounts.urls",namespace="discounts_app")),
    path('payment/', include("apps.payments.urls",namespace="payments_app")),
    path('what-cook/', include("apps.what_cook.urls",namespace="what_cook_app")),
    path('comments/', include("apps.comments.urls",namespace="comments_app")),
    path('ads/', include("apps.ad.urls",namespace="ad_app")),
    path('subscription/', include("apps.subscription.urls",namespace="subscription_app")),
    path('mukbang/', include("apps.mukbang.urls",namespace="mukbang_app")),
    path('gift/', include("apps.gift.urls",namespace="gift_app")),
    path('chat-gpt/', include("apps.chat_gpt.urls",namespace="chat_gpt_app")),
    # path('', include("googleauthentication.urls")),
    path('accounts/auth/', include("allauth.urls")),
    path('delivery/', include("apps.delivery.urls",namespace="delivery_app")),
)
    
handler404 = 'apps.main.views.http_status_404'
admin.site.site_header = _("پنل مدیریت سایت فودینو")
# admin.site.site_title = "صفحه اصلی"
admin.site.index_title = _("به پنل مدیریت سایت فودینو خوش آمدید.")

food/apps/message/views.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.shortcuts import render,redirect
from .models import *
from django.contrib.messages import success,error
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import requires_csrf_token
# Create your views here.

def show_box(request):
    try:
        chat_session=request.session['chat_session']
    except:
        return render(request,'partials/chat_box.html')

    return render(request,'partials/chat_box.html',{'chat_session':chat_session})

def add_message(request):
    if request.method == "POST":
        message = Message()
        message.name = request.POST['name']
        message.family = request.POST['family']
        message.email = request.POST['email']
        message.mobile_number = request.POST['mobile_number']
        message.subject = request.POST['subject']
        message.message = request.POST['message']
        message.save()
        success(request,_('پیام شما با موفقیت ارسال شد.'),'success')
        return redirect('main_app:index')
    return render(request,"message/contact_us/show.html")
def add_user_in_chat_room(request):
    if request.method == "POST" and not str(request.POST.get('full_name')) == "":
        full_name = request.POST.get('full_name')
        phone_number = request.POST.get('phone_number')
        avatar = request.POST.get('avatar')
        user=UserChatRoom.objects.filter(phone_number=phone_number)
        is_exists=user.exists()
        chat_info_dict = {'is_exist': True,'full_name': full_name,'phone_number': phone_number,'avatar':avatar,'messages_len':0}
        request.session['chat_session']=chat_info_dict
        if is_exists:
            user.update(full_name=full_name,phone_number=phone_number,is_exist=True,avatar=avatar)
        else:
            UserChatRoom.objects.create(full_name=full_name,phone_number=phone_number,is_exist=True,avatar=avatar)
        return redirect('message_app:show_chat')
    return render(request,"message/chat/partials/chatroom_add_user_form.html")
def add_message_online_chat(request):
    message=request.GET.get('message')
    try:
        user=UserChatRoom.objects.get(phone_number=request.session['chat_session']['phone_number'])
    except:
        return redirect("main_app:index")
    ChatRoom.objects.create(message_text=message,sender_user=user)
    return redirect("message_app:show_messages")

def show_messages(request):
    is_manage_chat = request.GET.get("is_manage_chat")
    print(100*'-')
    print(is_manage_chat)
    print(100*'-')
    if is_manage_chat == 'true':
        try:
            user = UserChatRoom.objects.get(phone_number=request.GET.get('phone_number'))
            # request.session['chat_session']['messages_len'] = len(user.message_user.all())
        except:
            print('error')
            # return redirect("main_app:index")
        return render(request,'message/chat/partials/chat_body.html',{'user_object':user,'is_manage_chat':is_manage_chat})    
    try:
        user = UserChatRoom.objects.filter(phone_number=request.session['chat_session']['phone_number'])[0]
        # request.session['chat_session']['messages_len'] = len(user.message_user.all())
        return render(request,'message/chat/partials/chat_body.html',{'user_object':user ,'is_manage_chat':is_manage_chat})    
    except:
        return redirect("message_app:start_online_chat")
        # <input type="hidden" value="" name="parent_id" id="id_parent_id">
        # <input type="hidden" value="{{user_object.phone_number}}" name="user_phone_number_input_hidden" id="id_user_phone_number_input_hidden">
def refresh_messages (request):
    if request.method == "POST":    
        user = UserChatRoom.objects.get(phone_number=request.POST.get('phone_number'))
        is_manage_chat = request.POST.get("is_manage_chat")
        length = len(user.message_user.all())
        print(100*'-')
        print(user)
        print(length)
        print(100*'-')
        if is_manage_chat == "true":
            request.session['chat_session']['messages_len'] = len(user.message_user.all())
            return render(request,'message/chat/partials/refresh_messages_manager.html',{'user_object':user ,'is_manage_chat':is_manage_chat})
        else:
            request.session['chat_session']['messages_len'] = len(user.message_user.all())
            return render(request,'message/chat/partials/refresh_messages_user.html',{'user_object':user,'is_manage_chat':'false' })
            
        # return HttpResponse("false")

def show_chat_room(request):
    return render(request,"message/chat/partials/show_chatroom.html",{'online_chat_data':request.session['chat_session']})

def clear_chat(request):
    try:
        ChatRoom.objects.get(sender_user=UserChatRoom.objects.get(phone_number=request.session['chat_session']['phone_number'])).delete()
        # request.session['chat_session'] = {}
    except:
        error(request,_("خطا در اجرای عملیات"),"error")
        return redirect('main_app:index')
    return redirect('message_app:show_messages')
def manage_chat_room(request):
    if request.user.is_support:
        try:
            user = UserChatRoom.objects.filter(phone_number=request.user.mobile_number)[0]
        except ObjectDoesNotExist:
            error(request,_("پشتیبان یافت نشد"), "error")
            return redirect('main_app:index') 
        else:
            if user.is_support:
                user_chat_rooms=UserChatRoom.objects.all()
                return render(request,'message/chat/manage_chat_room.html',{'user_chat_rooms':user_chat_rooms})
            else:
                error(request,_('شما اجازه ورود ندارید.'), 'error')
                return redirect('main_app:index')
    error(request,_('شما اجازه ورود ندارید.'), 'error')
    return redirect('main_app:index')

def show_messages_in_manage_chat_room(request):    
    phone_number = request.user.mobile_number
    try:
        user = UserChatRoom.objects.filter(phone_number=phone_number)[0]
    except:
        error(request,_("شما مجوز ورود به پنل مدیریت پیام‌ها را ندارید!"), "error")
        return redirect('message_app:show_messages_in_manage_chat_room')
    else:
        model=request.GET.get('model')
        parent_id=request.GET.get('parent_id')
        if model == 'send_message':
            if parent_id:
                ChatRoom.objects.create(
                    sender_user=user,
                    receiver_user=UserChatRoom.objects.get(phone_number=request.GET.get('receiver_user_phone_number')),
                    message_text=request.GET['message'],
                    message_parent = ChatRoom.objects.filter(id=request.GET['parent_id'])[0]
                    )
            else: 
                ChatRoom.objects.create(
                    sender_user=user,
                    receiver_user=UserChatRoom.objects.get(phone_number=request.GET.get('receiver_user_phone_number')),
                    message_text=request.GET['message'],
                    )   
            return render(request,'message/chat/partials/chat_body.html',{'user_object':user,'is_manage_chat':'true' ,'model':model})
        return render(request,'message/chat/partials/chat_body.html',{'user_object':user,'is_manage_chat':'true' })

food/templates/partials/indicator.html
<div class="indicator-wrapper">
    <div class="indicator"></div>
</div>

food/templates/partials/loading.html
<div class="loading-page">
    <div class="loading-circle"></div>
</div>

food/templates/partials/messages.html
{% load translate %}
{% load i18n %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}" id="alert_id_1">
    <i class="fa fa-times s-times" onclick="delete_element('alert_id_1')"></i>
    <div>
        {% if message.tags == "error error" %}
        <img src="{{media}}/images/alerts/error.svg">
        {% elif message.tags == "success success" %}
        <img src="{{media}}/images/alerts/success.svg">
        {% else %}
        <img src="{{media}}/images/alerts/danger.svg">
        {% endif %}
        {% if message.message == "login" %}
        <span>{% trans 'شما قبلا با این شماره ثبت‌نام کردید.' %}</span><a href="{% url 'accounts_app:login' %}" class="link" style="color:#555">{% trans 'وارد شوید.' %}</a>
        {% else %}
        <span>{{message.message|translate}}</<span>
        {% endif %}
    </div>
</div>
{% endfor %}
{% endif %}

food/templates/partials/navbar.html
{% load translate %}
{% load i18n %}
<ul id="id_navbar_number_2">
    <li>
        <span id="id_menu_bar_icon"><i class="fa fa-bars"></i></span>
        <ul>
            <li><a href="{% url 'main_app:index' %}"><i class="fa fa-home"></i> <span>{% trans 'خانه<' %}/span></a></li>
            <li>
                <span>{% trans 'دسته‌بندی‌ها' %}<i class="fa fa-angle-down"></i></span>
                <ul>
                    <li><a href="{% url 'food_app:show_food_groups' %}">{% trans 'دسته‌بندی غذاها' %}</a></li>
                </ul>
            </li>
            <li><a href="{% url 'what_cook_app:index' %}">{% trans 'چی بپزم' %}</a></li>
            <li><a href="{% url 'my_environment_app:my_environment_index' %}">{% trans 'محیط زیست من' %}</a></li>
            <li><a href="{% url 'blog_app:show_blogs' %}">{% trans 'بلاگ' %}</a></li>
            <li><a href="{% url 'subscription_app:index' %}">{% trans 'خرید اشتراک' %}</a></li>
            <li id="id_garune"><span>{% trans 'هدایا' %}<i class="fa fa-angle-down"></i></span>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'gift_app:show_wheel_of_luck' %}">{% trans 'گردانه‌ شانس' %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'gift_app:show_lotteries' %}">{% trans 'قرعه‌کشی' %}</a></li>
                </ul> 
            </li>
            {% if user.is_authenticated %}
            <li><span>{% trans 'حساب کاربری' %}<i class="fa fa-angle-down"></i></span>
                <ul>
                    {% if user.is_admin %}
                    <li><a href="{% url 'admin:index' %}">{% trans 'پنل مدیریت سایت' %}</a></li>
                    <li><a href="{% url 'data_manager_app:index' %}">{% trans 'پنل مدیریت داده' %}</a></li>
                    <li><a href="http://127.0.0.1:8000/rosetta">{% trans 'پنل مدیریت زبان سایت' %}</a></li>
                    {% endif %}
                    {% if user.is_serviceman %}
                    <li><a href="{% url 'orders_app:orders_panel' %}">{% trans 'پنل مدیریت سفارشات' %}</a></li>
                    {% endif %}
                    {% if user.is_support %}
                    <li><a href="http://127.0.0.1:8000/manage-chat-room">{% trans 'پنل مدیریت پیام‌ها' %}</a></li>
                    {% endif %}
                    {% if user.is_delivery %}
                    <li><a href="{% url 'delivery_app:delivery_panel' %}">{% trans 'پنل مدیریت پیک' %}</a></li>
                    {% endif %}
                    {% if user_info.is_user_compile %}
                    <li><a href="{% url 'accounts_app:compile_information' %}">{% trans 'تکمیل مشخصات' %}</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts_app:compile_information' %}">{% trans 'تغییر مشخصات' %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'accounts_app:user_panel' %}">{% trans 'پنل کاربری' %}</a></li>
                    <li><a href="{% url 'orders_app:carts' %}">{% trans 'سبد خرید' %}</a></li>
                    <li><span>{% trans 'امتیاز شما:' %}</span><span>{{user.score}}</span></li>
                    <li><a href="{% url 'accounts_app:logout' %}">{% trans 'خروج ' %}<i class="fa fa-sign-out"></i></a></li>
                </ul>
            </li>
            {% else %}
            <li><span>{% trans 'حساب کاربری' %}<i class="fa fa-angle-down"></i></span>
                <ul>
                    <li><a href="{% url 'accounts_app:register' %}">{% trans 'ثبت‌نام' %}</a></li>
                    <li><a href="{% url 'accounts_app:login' %}">{% trans 'ورود' %}</a></li>
                </ul>
            </li>
            {% endif %}
        </ul>
    </li>
    <li>
        <form class="form-search" action="{% url 'search_app:search_results' %}">
            <input class="form-search-input input" type="text" name="q" placeholder="{% trans 'جستجو از میان حصول' %} {{foods_length}} {% trans 'محصول' %}" value="{{query}}">
            <button class="search-btn"><i class="fa fa-search"></i></button>
        </form>
    </li>
    <!-- <li>
        <span id="id_menu_bar_icon"><i class="fa fa-search"></i>></span>
        <ul>
            <li></li>
        </ul>
    </li> -->
</ul>
<ul id="id_navbar_number_1">
    <li><a href="{% url 'main_app:index' %}"><img src="{{media}}images/logo/logo.png" alt="{% trans 'فودینو' %}" class="logo"></a></li>
    <li><a href="{% url 'main_app:index' %}"><i class="fa fa-home"></i> <span>{% trans 'خانه' %}</span></a></li>
    <li>
        <span>{% trans 'دسته‌بندی‌ها' %}<i class="fa fa-angle-down"></i></span>
        <ul>
            <li><a href="{% url 'food_app:show_food_groups' %}">{% trans 'دسته‌بندی غذاها' %}</a></li>
        </ul>
    </li>
    <li><a href="{% url 'what_cook_app:index' %}">{% trans 'چی بپزم' %}</a></li>
    <li id="my_environment"><a href="{% url 'my_environment_app:my_environment_index' %}">{% trans 'محیط زیست من' %}</a></li>
    <li><a href="{% url 'blog_app:show_blogs' %}">{% trans 'بلاگ' %}</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'subscription_app:index' %}">{% trans 'خرید اشتراک' %}</a></li>
    {% endif %}
    <li id="id_garune"><span>{% trans 'هدایا' %}<i class="fa fa-angle-down"></i></span>
        <ul>
            <li><a href="{% url 'gift_app:show_wheel_of_luck' %}">{% trans 'گردانه‌ شانس' %}</a></li>
            <li><a href="{% url 'gift_app:show_lotteries' %}">{% trans 'قرعه‌کشی' %}</a></li>
        </ul>
    </li>
    {% if user.is_authenticated %}
    <li><span>{% trans 'حساب کاربری' %}<i class="fa fa-angle-down"></i></span>
        <ul>
            {% if user.is_admin %}
            <li><a href="{% url 'admin:index' %}">{% trans 'پنل مدیریت سایت' %}</a></li>
            <li><a href="https://soheil.irandns.com:2083/cpsess8736874517/frontend/jupiter/index.html?login=1&post_login=93746244839147" target="_blank">{% trans 'سی پنل' %}</a></li>
            <li><a href="{% url 'data_manager_app:index' %}">{% trans 'پنل مدیریت داده' %}</a></li>
            <li><a href="http://127.0.0.1:8000/rosetta">{% trans 'پنل مدیریت زبان سایت' %}</a></li>
            {% endif %}
            {% if user.is_serviceman %}
                <li><a href="{% url 'orders_app:orders_panel' %}">{% trans 'پنل مدیریت سفارشات' %}</a></li>
            {% endif %}
            {% if user.is_support %}
            <li><a href="http://127.0.0.1:8000/manage-chat-room">{% trans 'پنل مدیریت پیام‌ها' %}</a></li>
            {% endif %}
            {% if user.is_delivery %}
            <li><a href="{% url 'delivery_app:delivery_panel' %}">{% trans 'پنل مدیریت پیک' %}</a></li>
            {% endif %}
            {% if user_info.is_user_compile %}
            <li><a href="{% url 'accounts_app:compile_information' %}">{% trans 'تکمیل مشخصات' %}</a></li>
            {% else %}
            <li><a href="{% url 'accounts_app:compile_information' %}">{% trans 'تغییر مشخصات' %}</a></li>
            {% endif %}
            <li><a href="{% url 'accounts_app:user_panel' %}">{% trans 'پنل کاربری' %}</a></li>
            <li><a href="{% url 'orders_app:carts' %}">{% trans 'سبد خرید' %}</a></li>
            <li><span>{% trans 'امتیاز شما:' %}</span><span>{{user.score}}</span></li>
            <li><a href="{% url 'accounts_app:logout' %}">{% trans 'خروج' %}</a></li>
        </ul>
    </li>
    {% else %}
    <li><span>حساب کاربری<i class="fa fa-angle-down"></i></span>
        <ul>
            <li><a href="{% url 'accounts_app:register' %}">{% trans 'ثبت‌نام' %}</a></li>
            <li><a href="{% url 'accounts_app:login' %}">{% trans 'ورود' %}</a></li>
        </ul>
    </li>
    {% endif %}
</ul>
<ul>
    <li id="id_favorites_icon"><a href="{% url 'favorites_app:user_favorite' %}"><span class="indicator-value" id="id_favorites_value"></span> <img src="{{media}}images/heart.png" alt="{% trans 'فودینو' %}" id="id_heart_image"></a></li>
    <li><a href="{% url 'orders_app:carts' %}"><span class="indicator-value" id="id_indicator-value"></span> <img src="{{media}}images/shop_cart/shopping-cart.png" alt="{% trans 'فودینو' %}" id="id_shopping_cart_image"></a></li>
</ul>

food/templates/partials/scripts.html
{% load static %}
<script src="{% static 'js/script.js' %}"></script>

food/templates/partials/top_menu.html
{% load render_partial %}
{% load translate %}
{% load i18n %}
{% render_partial 'event_app:show_top_menu_event' %}
<div class="top-menu-1">
    <div>
        <div><a href="{% url 'main_app:about_me' %}">{% trans 'درباره ما' %}</a></div>
        <div><a href="{% url 'message_app:contact_us' %}">{% trans 'تماس باما' %}</a></div>
        <div><a href="{% url 'main_app:show_frequently_asked_questions' %}">{% trans 'سوالت متداول' %}</a></div>
        {% if user.is_authenticated %}
        <div><a href="{% url 'accounts_app:user_panel' %}" id="id_user_panel">{% trans 'پنل کاربری' %}</a></div>
        {% endif %}
    </div>
</div>
<div class="top-menu-2">
    <div>
        <div>
            <img src="{{media}}images/top_menu/image.png" alt="" id="id_top_menu_image">
        </div>
        <div class="search-form-div">
            <form class="form-search" action="{% url 'search_app:search_results' %}">
                <input class="form-search-input input" type="text" name="q" placeholder="{% trans 'جستجو از میان' %} {{foods_length}} {% trans 'محصول' %}" value="{{query}}">
                <button class="search-btn"><i class="fa fa-search"></i></button>
            </form>
        </div>
        <div>
            <div>
                <span>{% trans 'پشتیبانی' %}</span>
            </div>
            <div>
                <a href="tel:09932062665"><span><small>021</small>-35368</span></a>
            </div>
        </div>
    </div>
</div>