food/apps/accounts/urls.py
from django.urls import path
from .views import *
app_name="accounts_app"
urlpatterns = [
    path('register/',RegisterUserView.as_view(),name='register'),
    path('compile-information/',CompileInformation,name='compile_information'),
    path('verify/',VerifyRegisterCodeView.as_view(),name='verify'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUserView.as_view(),name='logout'),
    path('user-panel/',user_panel,name='user_panel'),
    path('change-password/',ChangePasswordView.as_view(),name='change_password'),
    path('remember-password/',RememberPasswordView.as_view(),name='remember_password'),
    path('change-profile/',change_profile,name='change_profile'),
    path('show-my-gifts/',show_my_gifts,name='show_my_gifts'),
    path('show-my-messages/',show_my_messages,name='show_my_messages'),
    path('show-my-transactions/',show_my_transactions,name='show_my_transactions'),
    path('change-profile-and-full-name/',change_profile_and_full_name,name='change_profile_and_full_name'),
    path('save-location/',save_location,name='save_location'),
]

food/apps/comments/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="comments_app"
urlpatterns = [
    path('create-comment/<slug:slug>/<str:model>/', CommentView.as_view(), name="create_comment"),
    path('show-my-comments/', show_my_comments, name="show_my_comments"),
]

food/apps/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="food_app"
urlpatterns = [ 
    # path('add-food/', add_food,name="add_food"),
    # path('delete-food/<int:id>/', delete_food,name="delete"),
    # path('edit-food/<int:id>/', edit_food,name="edit_food"),
    path('show-food/<str:slug>/',show_food,name="show_food"),
    path('show-food-part/',show_food_info,name="show_food_info"),
    path('show-foods/group/<str:group_id>/',show_foods_g,name="show_foods_width_group"),
    path('show-foods/',show_foods,name="show_foods"),
    path('show-similar-foods/',show_similar_foods,name="show_similar_foods"),
    
    path('add-to-my-recipes/',add_to_my_recipes,name="add_to_my_recipes"),
    path('update-my-recipe/',update_my_recipe,name="update_my_recipe"),
    path('delete-my-recipe/',delete_my_recipe,name="delete_my_recipe"),
    path('show-my-recipes/',show_my_recipes,name="show_my_recipes"),
    path('show-my-recipe/<int:recipe_id>/',show_my_recipe,name="show_my_recipe"),
    
    path('add-food-group/', add_food_group,name="add_food_group"),
    path('delete-food-group/', delete_food_group,name="delete_food_group"),
    path('edit-food-group/', edit_food_group,name="edit_food_group"),
    path('show-food-groups/',show_food_groups,name="show_food_groups"),
    
    path('add-recipes/',add_recipes,name="add_recipes"),
    path('delete-recipes/<int:id>/',delete_recipes,name="delete_recipes"),
    path('edit-recipes/',edit_recipes,name="edit_recipes"),
    path('show-recipe/<str:slug>/',show_recipes,name="show_recipe"),
    path('recipe/<int:id>/',show_recipe_with_id,name="show_recipe_with_id"),
    path('show-recipes/',show_all_recipes,name="show_recipes"),
    path('add-like-recipe/',add_like_recipe,name="add_like_recipe"),
    path('add-dislike-recipe/',add_dislike_recipe,name="add_dislike_recipe"),
    
    path('what',what_food,name="what_food"),
    
    path('show-comments/',show_comments,name="show_comments"),
]

food/apps/main/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name='main_app'
urlpatterns = [
    path('', index,name='index'),
    path('about-me/', about_me,name='about_me'),
    path('rules/', rules,name='rules'),
    path('show-frequently-asked-questions/', show_frequently_asked_questions,name='show_frequently_asked_questions'),
    path('download/<str:content_type>/<str:file_path>/', download,name='download'),
    path('save-image/', save_image,name='save_image'),   
]

# handler404 = 'apps.main.views.http_status_404'

food/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""food URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path('scores/', include("apps.scores.urls",namespace="scores_app")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

urlpatterns+=i18n_patterns(
    path('', include("apps.message.urls",namespace="message_app")),
    path('favorites/', include("apps.favorites.urls",namespace="favorites_app")),
    path('my-environment/', include("apps.my_environment.urls",namespace="my_environment_app")),
    path('data-manager/', include("apps.data_manager.urls",namespace="data_manager_app")),
    path('event/', include("apps.event.urls",namespace="event_app")),
    path('language/', include("apps.language.urls",namespace="language_app")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('', include("apps.main.urls",namespace="main_app")),
    path('food/', include("apps.food.urls",namespace="food_app"),name="food_app"),
    path('blog/', include("apps.blog.urls",namespace="blog_app"),name="blog_app"),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('orders/', include("apps.orders.urls",namespace="orders_app")),
    path('accounts/', include("apps.accounts.urls",namespace="accounts_app")),
    path('search/', include("apps.search.urls",namespace="search_app")),
    path('discounts/', include("apps.discounts.urls",namespace="discounts_app")),
    path('payment/', include("apps.payments.urls",namespace="payments_app")),
    path('what-cook/', include("apps.what_cook.urls",namespace="what_cook_app")),
    path('comments/', include("apps.comments.urls",namespace="comments_app")),
    path('ads/', include("apps.ad.urls",namespace="ad_app")),
    path('subscription/', include("apps.subscription.urls",namespace="subscription_app")),
    path('mukbang/', include("apps.mukbang.urls",namespace="mukbang_app")),
    path('gift/', include("apps.gift.urls",namespace="gift_app")),
    path('chat-gpt/', include("apps.chat_gpt.urls",namespace="chat_gpt_app")),
    # path('', include("googleauthentication.urls")),
    path('accounts/auth/', include("allauth.urls")),
    path('delivery/', include("apps.delivery.urls",namespace="delivery_app")),
)
    
handler404 = 'apps.main.views.http_status_404'
admin.site.site_header = _("پنل مدیریت سایت فودینو")
# admin.site.site_title = "صفحه اصلی"
admin.site.index_title = _("به پنل مدیریت سایت فودینو خوش آمدید.")

food/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractBaseUser,PermissionsMixin,BaseUserManager,UserManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from apps.gift.models import Gift
__version__ = "1.1.0"
# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self,mobile_number,email="",name="",family="",active_code=None,gender=None,password=None):
        if not mobile_number:
            raise ValueError(_("شماره موبایل باید وارد شود"))
        if len(mobile_number)<11:
            raise ValueError(_('شماره موبایل وارد شده صحیح نمی باشد.'))
        user = self.model(
            mobile_number=mobile_number,
            email=self.normalize_email(email),
            name=name,
            family=family,
            active_code=active_code,
            gender=gender,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,mobile_number,email,name,family,password=None,active_code=None,gender=None):
        user=self.create_user(
            mobile_number=mobile_number,
            email=email,
            name=name,
            family=family,
            active_code=active_code,
            gender=gender,
            password=password,
        )
        user.is_active = True
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
# start class Country
class Country(models.Model):
    class_name="Country"
    name = models.CharField(max_length=250,verbose_name=_("نام کشور"),help_text=_("نام کشوری که در آن خدمات صورت می گیرد را وارد کنید."))
    photo_of_the_flag = models.ImageField(upload_to='images/account/country',verbose_name=_("عکس پرجم کشور") ,default="images/account/country/NaN.png", null=True,blank=True,help_text=_("تصویر پرچم کشوری که در آن خدمات صورت می گیرد را وارد کنید. نکته : بهتر است از تصویر با فرمت webp استفاده کنید تا سرعت سایت به مشکل بر نخورد"))
    telephone_code = models.CharField(max_length=50,default="+98",help_text=_("در این قسمت باید کد پیش شماره کشور را وارد کنید تا در زمان ارسال پیامک کدپیش شماره ابتدای شماره تماس کاربر بیفتد."),null=True,blank=True)
    is_translated_content = models.BooleanField(default=False,verbose_name=_("آیا محتوا ترجمه شده؟"))
    def fields_information(self):
        return [{"field_name":"id","verbose_name":'id',"value":self.id},{"field_name":"photo_of_the_flag","verbose_name":"تصویر پرچم کشور","value":self.photo_of_the_flag},{'field_name':'name',"verbose_name":"نام کشور","value":self.name},{'field_name':'telephone_code',"verbose_name":"کدپیش شماره کشور","value":self.telephone_code}]
    # def __dict__(self):
    #     return {"name":self.name,"photo_of_the_flag":self.photo_of_the_flag,"telephone_code":self.telephone_code}
    def __str__(self):
        return f"{self.name}"
    class Meta:
        verbose_name = _("کشور")
        verbose_name_plural = _("کشورها")
        db_table ="table_country"

# end class Country   
# start class State   
class State(models.Model):
    class_name = "State"
    name = models.CharField(max_length=50,verbose_name=_("نام استان"),help_text=_("استانی که در آن خدمات صورت می‌گیرد آن را وارد کنید."))
    country = models.ForeignKey(Country,verbose_name=_("کشور"),on_delete=models.CASCADE,null=True,blank=True,help_text=_("استان در کدام کشور است؟ آن را وارد کنید."))
    is_translated_content = models.BooleanField(default=False,verbose_name=_("آیا محتوا ترجمه شده؟"))
    is_translated_content = models.BooleanField(default=False,verbose_name=_("آیا محتوا ترجمه شده؟"))
    def fields_information(self):
        return [{"field_name":"id","verbose_name":'id',"value":self.id},{"field_name":"name","verbose_name":"نام استان یا ایالت","value":self.name},{"field_name":"country","verbose_name":"کشور","value":self.country}]
    def __str__(self):
        return f"{self.name} {self.country}"
    class Meta:
        verbose_name = _("استان")
        verbose_name_plural = _("استان‌ها")
        db_table ="table_state"
# end class State   
# start class City   
class City(models.Model):
    class_name = "City"
    name = models.CharField(max_length=200,verbose_name=_("نام شهر"),help_text=_("شهری که در آن خدمات صورت می‌گیرد را وارد کنید."))
    country = models.ForeignKey(Country,verbose_name=_("کشور"),on_delete=models.CASCADE,null=True,blank=True,help_text=_("شهر در کدام کشور قرار دارد آن را وارد کنید."))
    is_translated_content = models.BooleanField(default=False,verbose_name=_("آیا محتوا ترجمه شده؟"))
    def fields_information(self):
        return [{"field_name":"id","verbose_name":'id',"value":self.id},{"field_name":"country","verbose_name":'کشور',"value":self.country},{"field_name":"name","verbose_name":"نام شهر","value":self.name}]
    def __str__(self):
        return f"{self.name}"
    class Meta:
        verbose_name = _("شهر")
        verbose_name_plural = _("شهرها")
        db_table ="table_city"
# end class City   
# start class CustomUser   
class CustomUser(AbstractBaseUser,PermissionsMixin):
    class_name = "CustomUser" 
    mobile_number = models.CharField(max_length=11,verbose_name=_("شماره موبایل"),unique=True,null=True,blank=True,help_text=_("شماره موبایل کاربر جدید را وارد کنید. نکته: شماره تماس کاربر نمی‌تواند تکراری باشد."))
    username = models.CharField(max_length=20,verbose_name=_("نام کاربری"),unique=True,null=True,blank=True)
    name = models.CharField(max_length=50,blank=True, verbose_name=_("نام"),help_text=_("نام کاربر را وارد کنید. نکته: این فیلد اجباری نیست."))
    family = models.CharField(max_length=50,blank=True, verbose_name=_("نام خانوادگی"),help_text=_("نام خانوادگی کاربر را وارد کنید. نکته: این فیلد اجباری نیست."))
    profile = models.ImageField(upload_to='images/account/profile',verbose_name=_("پروفایل") ,default="images/account/profile/NaN.png", null=True,blank=True,help_text=_("تصویر کاربر را بارگذاری کنید. نکته:بهتراست از تصاویری به فرمت webp استفاده کنید تا سرعت سایت به مشکل برنخورد. نکته: این فیلد اجباری نیست."))
    email = models.EmailField(max_length=200,blank=True,verbose_name=_("ایمیل"),help_text=_("ایمیل کاربر را وارد کنید. در صورتی که کاربر ایمیل خود را وارد کرده باشد ایمیل‌هایی از طرف سایت برای او ارسال می‌شود"))
    GENDER_CHOICES=(('True',_('مرد')),('False',_('زن')))
    gender= models.CharField(max_length=50,blank=True,choices=GENDER_CHOICES,default='True',null=True, verbose_name="جنسیت",help_text=_("نکته: این فیلد اجباری نیست."))
    address = models.TextField(max_length=500,verbose_name=_("آدرس"),help_text=_("لطفا آدرس محل زنگی کاربر را به درستی وارد کنید. نکته: این فیلد در زمان ثبت‌نام اجباری نیست."))
    latitude_location = models.CharField(max_length=15,blank=True,null=True,verbose_name=_("عرض جغرافیایی کاربر"))
    longitude_location = models.CharField(max_length=15,blank=True,null=True,verbose_name=_("طول جغرافیایی کاربر"))
    country = models.ForeignKey(Country,verbose_name=_("کشور"),on_delete=models.CASCADE,null=True,blank=True,help_text=_("کشوری که کاربر در آن زندگی می کند."))
    state = models.ForeignKey(State,verbose_name=_("استان"),on_delete=models.CASCADE,null=True,blank=True,help_text=_("استانی که کاربر در آن زندگی می کند."))
    city = models.ForeignKey(City,verbose_name=_("شهر"),on_delete=models.CASCADE,null=True,blank=True,help_text=_("شهری که کاربر در آن زندگی می کند."))
    birth_date = models.DateField(null=True,verbose_name=_("تاریخ تولد"),blank=True,help_text=_("تاریخ تولد کار بر را وارد کنید. با وارد کردن تاریخ تولد کاربر روز تولد آن پیام تبریک برای آن ارسال می‌شود."))
    score = models.IntegerField(default=20,verbose_name=_("امتیاز"),help_text=_("امتیاز کاربر امتیازی است که با هر خرید به آن اضافه می شود. و با آن می‌تواند گردونه شانس را فعال کند."))
    national_code = models.CharField(null=True,verbose_name=_("کدملی"),blank=True, max_length=11,help_text=_("لظفا کدملی کاربر را درست وارد کنید زیرا که اگر مشکلی به وجود بی آید با آن کارهای قانونی انجام شود."))
    postal_code = models.CharField(null=True,verbose_name=_("کدپستی"),blank=True, max_length=10,help_text=_("لطفا کدپستی کاربر را وارد کنید تا سایت بتواند خدمات بهتری به کاربر بدهد"))
    register_date= models.DateField(default=timezone.now, verbose_name=_("تاریخ ثبت نام"),help_text=_("تاریخ ثبت‌نام کاربر به ضورت خودکار نوشته می‌شود."))
    is_complete_information = models.BooleanField(default=False,verbose_name=_("اطلاعات کامل است؟"),help_text=_("در صورتی که کاربر تمامی اطلاعات را داده باشد این تیک فعال می شود."))
    is_active = models.BooleanField(default=False, verbose_name="وضعیت فعال/غیرفعال",help_text=_("با این فیلد شما می‌توانید کابر را فعال و یا غیر فعال کنید."))
    active_code= models.CharField(max_length=100,null=True, blank=True, verbose_name=_("کد فعال سازی"),help_text=_("کدفعال سازی کدی است که به صورت خودکار ساخته می شود و برای راستی آزمایی کاربر به او پیانک می‌شود و کاربر می تواند با وارد کردن آن کاربر فعال شود."))
    gifts = models.ManyToManyField(Gift,verbose_name=_("هدایای کاربر"),help_text=_("هدایایی است که کاربر طی فعالیت ها دریافت می کند."),blank=True)
    current_order = models.PositiveIntegerField(default=0,verbose_name=_("تعداد سفارش جاری"))
    delivered_order = models.PositiveIntegerField(default=0,verbose_name=_("تعداد سفارش تحویل داده شده"))
    returned_order = models.PositiveIntegerField(default=0,verbose_name=_("تعداد سفارش مرجوع شده"))
    is_admin = models.BooleanField(default=False, verbose_name=_("مدیر است بله/خیر"),help_text=_("در صورتی که این تیک فعال شود کاربر مدیر سایت شناخته می شود و به برخی از قسمت‌های خصوصی دسترسی پیدا میکند. توجه: درصورتی که کاربر خلاف کار باشد باعث به خطر افتادن اطلاعات سایت می‌شود در تایین وضعیت این فیلد بسیار دقت کنیدو"))
    is_support = models.BooleanField(default=False, verbose_name=_("پشتیبان است بله/خیر"),help_text=_("درصورتی که این تیک را فعال کنید کاربر به عنوان پشتیبان شناخته می شود و دسترسی به پنل پیام ها دسترسی پیدا می کند."))

food/templates/accounts/more_info.html
{% extends 'main_template.html' %}
{% load translate %}
{% load i18n %}
{% block title %}{% trans 'تکمیل مشخصات' %}{% endblock title %}
{% block header %} 
{% endblock header %}
{% block main %}
<section>
    <div class="title">
        <h2>{% trans 'تکمیل مشخصات' %}</h2>
    </div>
    <div>
        {{form.as_p}}
    </div>
</section>
{% endblock main %}
    

food/templates/accounts/user_panel.html
{% extends 'main_template.html' %}
{% load translate %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'پنل کاربری' %}{% endblock title %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/user_panel.css' %}">
{% endblock stylesheet %}
{% block header %}
{% endblock header %}
{% block main %}
<aside class="aside-user-panel">
    <ul>
        <li id="id_profile_information">
            <div>
                <div>
                    <img class="profile" src="{{media}}{{user.profile}}" alt="" id="user_profile">
                </div>
                <div>
                    {% if user.is_admin %}
                    <span>
                        <img src="{{media}}images/account/user_panel/blue-tick.svg" alt="" class="blue-tick">
                        {{user.name|translate}} {{user.family|translate}}
                    </span>
                    <span id="profile_information_mobile_number">{{user.mobile_number}}</span>
                    {% else %}
                    <span>
                        {{user.name|translate}} {{user.family|translate}}
                    </span>
                    <span>{{user.mobile_number}}</span>
                    {% endif %}
                </div>
                <div>
                    <a id="change_profile_and_full_name_btn"><i class="fa fa-edit"></i></a>
                </div>
            </div>
        </li>
        {% if user.is_admin %}
        <li>
            <div>
                <a href="{% url 'admin:index' %}" class="user-menu-btn">
                    <div><i class="fa fa-cog"></i></div>
                    <div>
                        {% trans 'پنل مدیریت سایت' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="https://soheil.irandns.com:2083/cpsess8736874517/frontend/jupiter/index.html?login=1&post_login=93746244839147" target="_blank" class="user-menu-btn">
                    <div><i class="fa ">CP</i></div>
                    <div>
                        {% trans 'سی پنل' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'data_manager_app:index' %}" class="user-menu-btn">
                    <div><i class="fa fa-database"></i></div>
                    <div>
                        {% trans 'پنل مدیریت داده' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="http://127.0.0.1:8000/rosetta" class="user-menu-btn">
                    <div><i class="fa fa-language"></i></div>
                    <div>
                        {% trans 'پنل مدیریت زبان سایت' %}
                    </div>
                </a>
            </div>
        </li>
        {% endif %}
        <li>
            <div>
                <a href="{% url 'favorites_app:user_favorite' %}" class="user-menu-btn">
                    <div><i class="fa fa-heart"></i></div>
                    <div>
                        {% trans 'لیست علافه‌مندی‌ها' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'food_app:show_my_recipes' %}" class="user-menu-btn">
                    <div><i class="fa fa-spoon"></i></div>
                    <div>
                        {% trans 'دستورات غذایی من' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'comments_app:show_my_comments' %}" class="user-menu-btn">
                    <div><i class="fa fa-comments"></i></div>
                    <div>
                        {% trans 'دیدگاه‌ها' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'accounts_app:show_my_messages' %}" class="user-menu-btn">
                    <div><i class="fa fa-comment"></i></div>
                    <div>
                        {% trans 'پیغام‌ها' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'accounts_app:show_my_gifts' %}" class="user-menu-btn">
                    <div><i class="fa fa-gift"></i></div>
                    <div>
                        {% trans 'هدایای من' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'accounts_app:show_my_transactions' %}" class="user-menu-btn">
                    <div><i class="fa fa-credit-card"></i></div>
                    <div>
                        {% trans 'تراکنش‌ها' %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'accounts_app:compile_information' %}" class="user-menu-btn">
                    <div><i class="fa fa-address-card-o"></i></div>
                    <div>
                        {% if user_info.is_user_compile %}
                        {% trans 'تکمیل مشخصات' %}
                        {% else %}
                        {% trans 'تغییر مشخصات' %}
                        {% endif %}
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div>
                <a href="{% url 'accounts_app:logout' %}" class="user-menu-btn">
                    <div><i class="fa fa-sign-out"></i></div>
                    <div>
                        {% trans 'خروج' %}
                    </div>
                </a>
            </div>
        </li>
    </ul>
</aside>
<section>
    <div class="user-panel-part" style="margin: 8px auto">
        <div class="title">
            <h2>{% trans 'سفارش‌های من' %}</h2>
        </div>
        <div>
            <div class="container orders" id="id_user_panel_orders_box">
                <div class="container orders">
                    <div><img src="{{media}}images/account/user_panel/status-processing.svg" alt=""></div>
                    <div>
                        <h3> {% trans 'سفارش' %}</h3>
                        <h4><span class="orders-number-of-mod">{{user.current_order}}</span>{% trans 'جاری' %}</h4>
                    </div>
                </div>
                <div class="container orders">
                    <div><img src="{{media}}images/account/user_panel/status-delivered.svg" alt=""></div>
                    <div>
                        <h3> {% trans 'سفارش' %}</h3>
                        <h4><span class="orders-number-of-mod">{{user.delivered_order}}</span>{% trans 'تحویل شده' %}</h4>
                    </div>
                </div>
                <div class="container orders">
                    <div><img src="{{media}}images/account/user_panel/status-returned.svg" alt=""></div>
                    <div>
                        <h3> {% trans 'سفارش' %}</h3>
                        <h4><span class="orders-number-of-mod">{{user.returned_order}}</span>{% trans 'مرجوع شده' %}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% if  last_orders %}
<section class="box-model-3" id="user_panel_section_2">
    <div>
        <div class="title">
        <h2>{% trans 'سفارشات اخیر' %}</h2>
    </div>
    <div class="container" style="width: 98%;">
        <table class="table-recent-orders">
            <thead>
                <tr>
                    <td>{% trans 'ردیف' %}a</td>
                    <td>{% trans 'کیوارکد' %}</td>
                    <td>{% trans 'سفارش' %}</td>
                    <td>{% trans 'تاریخ' %}</td>
                    <td>{% trans 'وضعیت' %}</td>
                    <td>{% trans 'جمع کل' %}</td>
                </tr>
            </thead>
            <tbody>
            {% for last_order in last_orders %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <div class="show-image-class-default">
                        <img src="{{media}}{{last_order.qr_code_image}}" alt="">
                    </div>
                </td>
                <td>{{last_order.order_code}}</td>
                <td>{{last_order.register_date}}</td>
                <td>{{last_order.status.order_status_title|translate}}</td>
                <td><span class="price">{{last_order.get_order_total_price}}</span> <span>{% trans 'تومان' %}</span></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>            
    </div>      
</section>
{% elif last_see %}
<section class="box-model-3" id="user_panel_section_2">
    <div>
        <div class="title">
        <h2>{% trans 'سفارشات اخیر' %}</h2>
    </div>
    <div class="container" style="width: 98%;">
    </div>      
</section>
{% endif %}
{% comment %}
{% render_partial 'orders_app:show_food_cart' %}
{% endcomment %}
{% endblock main %}
{% block script %}
<script src="{% static 'js/show_image_scripts.js' %}"></script>
<script src="{% static 'js/user_panel_script.js' %}"></script>
{% endblock script %}

food/templates/accounts/verify_register_code.html
{% extends 'main_template.html' %}
{% load translate %}
{% load i18n %}
{% block title %}{% trans 'تایید شماره موبایل' %}{% endblock title %}
{% block header %}
{% endblock header %}
{% block main %}
<div class="container">
    <form action="" method="post">
        <div class="form-box">
            <div>
                <h1>{% trans 'تایید شماره موبایل<' %}/h1>
            </div>
            {% csrf_token %}
            {{form.as_p}}
            <div>
                <input type="submit" value="{% trans 'تایید' %}">
            </div> 
        </div>
    </form>
</div>
{% endblock main  %}