food/apps/blog/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="blog_app"
urlpatterns = [
    path('add-key-word/', add_key_word, name="add_key_word"),
    path('delete-key-word/<int:id>/', add_key_word, name="delete_key_word"),
    path('edit-key-word/<int:id>/', edit_key_word, name="edit_key_word"),
    path('show-key-word/<int:id>/', show_key_word, name="show_key_word"),
    path('show-key-words/', show_key_words, name="show_key_words"),
    
    path('add-blog/', add_article, name="add_blog"),
    path('delete-blog/<str:slug>/', add_article, name="delete_blog"),
    path('edit-blog/<str:slug>/', edit_article, name="edit_blog"),
    path('show-blog/<str:slug>/', show_article, name="show_blog"),
    path('<int:id>/', show_article_with_id, name="show_article_with_id"),
    path('show-blogs/', show_all_article, name="show_blogs"),
    path('show-blogs-with-author//<str:author_slug>/', show_article_with_author, name="show_article_with_author"),
    
    path('add-author/', add_author, name="add_author"),
    path('delete-author/<str:slug>/', add_author, name="delete_author"),
    path('edit-author/<str:slug>/', edit_author, name="edit_author"),
    path('show-author/<str:slug>/', show_author, name="show_author"),
    path('show-authors/', show_all_author, name="show_authors"),
    
    
    path('add-like/', add_like, name="add_like"),
    path('add-dislike/', add_dislike, name="add_dislike"),
]

food/apps/favorites/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="favorites_app"
urlpatterns = [
    path('add-to-favorite/', add_to_favorite, name="add_to_favorite"),
    path('delete-to-favorite/', delete_to_favorite, name="delete_to_favorite"),
    path('add-to-favorite-blog/', add_to_favorite_blog, name="add_to_favorite_blog"),
    path('delete-to-favorite-blog/', delete_to_favorite_blog, name="delete_to_favorite_blog"),
    
    path('status-of-favorite/', status_of_favorite, name="status_of_favorite"),
    
    path('user-favorite/', UserFavoriteView.as_view(), name="user_favorite"),
] 

food/apps/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.urls import path
from .views import *
app_name="food_app"
urlpatterns = [ 
    # path('add-food/', add_food,name="add_food"),
    # path('delete-food/<int:id>/', delete_food,name="delete"),
    # path('edit-food/<int:id>/', edit_food,name="edit_food"),
    path('show-food/<str:slug>/',show_food,name="show_food"),
    path('show-food-part/',show_food_info,name="show_food_info"),
    path('show-foods/group/<str:group_id>/',show_foods_g,name="show_foods_width_group"),
    path('show-foods/',show_foods,name="show_foods"),
    path('show-similar-foods/',show_similar_foods,name="show_similar_foods"),
    
    path('add-to-my-recipes/',add_to_my_recipes,name="add_to_my_recipes"),
    path('update-my-recipe/',update_my_recipe,name="update_my_recipe"),
    path('delete-my-recipe/',delete_my_recipe,name="delete_my_recipe"),
    path('show-my-recipes/',show_my_recipes,name="show_my_recipes"),
    path('show-my-recipe/<int:recipe_id>/',show_my_recipe,name="show_my_recipe"),
    
    path('add-food-group/', add_food_group,name="add_food_group"),
    path('delete-food-group/', delete_food_group,name="delete_food_group"),
    path('edit-food-group/', edit_food_group,name="edit_food_group"),
    path('show-food-groups/',show_food_groups,name="show_food_groups"),
    
    path('add-recipes/',add_recipes,name="add_recipes"),
    path('delete-recipes/<int:id>/',delete_recipes,name="delete_recipes"),
    path('edit-recipes/',edit_recipes,name="edit_recipes"),
    path('show-recipe/<str:slug>/',show_recipes,name="show_recipe"),
    path('recipe/<int:id>/',show_recipe_with_id,name="show_recipe_with_id"),
    path('show-recipes/',show_all_recipes,name="show_recipes"),
    path('add-like-recipe/',add_like_recipe,name="add_like_recipe"),
    path('add-dislike-recipe/',add_dislike_recipe,name="add_dislike_recipe"),
    
    path('what',what_food,name="what_food"),
    
    path('show-comments/',show_comments,name="show_comments"),
]

food/food/urls.py
# File version
__version__ = "1.1.1"
# File Description
"""food URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path('scores/', include("apps.scores.urls",namespace="scores_app")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

urlpatterns+=i18n_patterns(
    path('', include("apps.message.urls",namespace="message_app")),
    path('favorites/', include("apps.favorites.urls",namespace="favorites_app")),
    path('my-environment/', include("apps.my_environment.urls",namespace="my_environment_app")),
    path('data-manager/', include("apps.data_manager.urls",namespace="data_manager_app")),
    path('event/', include("apps.event.urls",namespace="event_app")),
    path('language/', include("apps.language.urls",namespace="language_app")),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('', include("apps.main.urls",namespace="main_app")),
    path('food/', include("apps.food.urls",namespace="food_app"),name="food_app"),
    path('blog/', include("apps.blog.urls",namespace="blog_app"),name="blog_app"),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('rosetta/', include('rosetta.urls')),
    path('orders/', include("apps.orders.urls",namespace="orders_app")),
    path('accounts/', include("apps.accounts.urls",namespace="accounts_app")),
    path('search/', include("apps.search.urls",namespace="search_app")),
    path('discounts/', include("apps.discounts.urls",namespace="discounts_app")),
    path('payment/', include("apps.payments.urls",namespace="payments_app")),
    path('what-cook/', include("apps.what_cook.urls",namespace="what_cook_app")),
    path('comments/', include("apps.comments.urls",namespace="comments_app")),
    path('ads/', include("apps.ad.urls",namespace="ad_app")),
    path('subscription/', include("apps.subscription.urls",namespace="subscription_app")),
    path('mukbang/', include("apps.mukbang.urls",namespace="mukbang_app")),
    path('gift/', include("apps.gift.urls",namespace="gift_app")),
    path('chat-gpt/', include("apps.chat_gpt.urls",namespace="chat_gpt_app")),
    # path('', include("googleauthentication.urls")),
    path('accounts/auth/', include("allauth.urls")),
    path('delivery/', include("apps.delivery.urls",namespace="delivery_app")),
)
    
handler404 = 'apps.main.views.http_status_404'
admin.site.site_header = _("پنل مدیریت سایت فودینو")
# admin.site.site_title = "صفحه اصلی"
admin.site.index_title = _("به پنل مدیریت سایت فودینو خوش آمدید.")

food/apps/favorites/models.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.db import models
from apps.food.models import Food
from apps.accounts.models import CustomUser
from apps.blog.models import Article
from django.utils.translation import gettext_lazy as _
# Create your models here.

class Favorite(models.Model):
    class_name = "Favorite"
    food = models.ForeignKey(Food,on_delete=models.CASCADE,related_name="favorite_food",verbose_name=_("غذا"))
    favorite_user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="favorite_user",verbose_name=_("کاربر علاقه مند"))
    register_date = models.DateTimeField(auto_now_add=True,verbose_name=_("تاریخ درج"))
    def fields_information(self):
        return [{"field_name":"id","verbose_name":'id',"value":self.id},{"field_name":"food","verbose_name":'فذا مورد علاقه',"value":self.food},{"field_name":"favorite_user","verbose_name":"کاربری که غذا را به علافه خود افزوده است","value":self.favorite_user},{"field_name":"register_date","verbose_name":"تاریخ درج","value":self.register_date}]
    def __str__(self):
        return f"{self.food} - {self.favorite_user}"
    class Meta:
        verbose_name = _("غذای مورد علاقه")
        verbose_name_plural = _("غذاهای مورد علاقه")
         
class Favorite_Blog(models.Model):
    class_name = "Favorite_Blog"
    blog = models.ForeignKey(Article,on_delete=models.CASCADE,related_name="favorite_blog",verbose_name=_("مقاله"))
    favorite_user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="favorite_blog_user",verbose_name=_("کاربر علاقه مند"))
    register_date = models.DateTimeField(auto_now_add=True,verbose_name=_("تاریخ درج"))
    def fields_information(self):
        return [{"field_name":"id","verbose_name":'id',"value":self.id},{"field_name":"blog","verbose_name":'مقاله مورد علاقه',"value":self.blog},{"field_name":"favorite_user","verbose_name":"کاربری که غذا را به علافه خود افزوده است","value":self.favorite_user},{"field_name":"register_date","verbose_name":"تاریخ درج","value":self.register_date}]
    def __str__(self):
        return f"{self.blog} - {self.favorite_user}"
    class Meta:
        verbose_name = _("مقاله‌ی مورد علاقه")
        verbose_name_plural = _("مقاله‌های مورد علاقه")

food/apps/favorites/views.py
# File version
__version__ = "1.1.1"
# File Description
"""
this python file
"""
from django.shortcuts import render,redirect
from apps.food.models import Food
from apps.blog.models import Article
from .models import *
from django.db.models import Q
from django.http import HttpResponse
from django.views import View
from django.contrib.messages import error,success
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import requires_csrf_token
# Create your views here.

def add_to_favorite(request):
    if request.method == "POST":
        food_id = request.POST.get('food_id')
        try:
            food=Food.objects.get(id=food_id)
        except:
            error(request, "همچین غذایی وجود ندارد!","error")
            redirect('favorit_app')
        flag = Favorite.objects.filter(Q(favorite_user_id=request.user.id) & Q(food_id=food_id)).exists()
        if not flag:
            Favorite.objects.create(food=food, favorite_user=request.user)
            return HttpResponse(_('این غذا به لیست علایق شما اضافه شد.'))
        return HttpResponse(_('این غذا قبلا در لیست غلایق شما قرار گرفته است.'))

def delete_to_favorite(request):
    if request.method == "POST":
        food_id = request.POST.get('food_id')
        try:
            food=Food.objects.get(id=food_id)
        except:
            error(request, "همچین غذایی وجود ندارد!","error")
            redirect('favorites_app:user_favorite')
        flag = Favorite.objects.filter(Q(favorite_user_id=request.user.id) & Q(food_id=food_id)).exists()
        if flag:
            Favorite.objects.filter(food=food, favorite_user=request.user)[0].delete()
            return HttpResponse(_('این غذا از لیست علایق شما حذف شد.'))
        return HttpResponse(_('این غذا قبلا در لیست غلایق شما وجود نداشت.'))

def status_of_favorite(request):
    print(100*'-')
    print(request.method)
    print(100*'-')
    if request.method == "POST":
        return HttpResponse(len(Favorite.objects.filter(Q(favorite_user_id=request.user.id))) + len(Favorite_Blog.objects.filter(Q(favorite_user_id=request.user.id))))

def add_to_favorite_blog(request):
    if request.method == "POST":
        blog_id = request.POST.get('blog_id')
        try:
            blog=Article.objects.get(id=blog_id)
        except:
            error(request, _("همچین غذایی وجود ندارد!"),"error")
            redirect('favorit_app:user_favorite')
        flag = Favorite_Blog.objects.filter(Q(favorite_user_id=request.user.id) & Q(blog_id=blog_id)).exists()
        if not flag:
            Favorite_Blog.objects.create(blog=blog, favorite_user=request.user)
            return HttpResponse(_('این مقاله به لیست علایق شما اضافه شد.'))
        return HttpResponse(_('این مقاله قبلا در لیست غلایق شما قرار گرفته است.'))
    

def delete_to_favorite_blog(request):
    if request.method == "POST":
        blog_id = request.POST.get('blog_id')
        try:
            blog=Article.objects.get(id=blog_id)
        except:
            error(request, _("همچین مقاله‌ای وجود ندارد!"),"error")
            redirect('favorites_app:user_favorite')
        flag = Favorite_Blog.objects.filter(Q(favorite_user_id=request.user.id) & Q(blog_id=blog_id)).exists()
        if flag:
            Favorite_Blog.objects.filter(blog=blog, favorite_user=request.user)[0].delete()
            return HttpResponse(_('این مقاله از لیست علایق شما حذف شد.'))
        return HttpResponse(_('این مقاله قبلا در لیست غلایق شما وجود نداشت.'))


class UserFavoriteView(View):
    def get(self, request, *args, **kwargs):
        favorite_food_user = Favorite.objects.filter(Q(favorite_user_id=request.user.id))
        favorite_blog_user = Favorite_Blog.objects.filter(Q(favorite_user_id=request.user.id))
        return render(request, 'favorites/user_favorite.html',{'favorite_food_user':favorite_food_user,'favorite_blog_user':favorite_blog_user})

food/templates/favorites/user_favorite.html
{% extends 'main_template.html' %}
{% load render_partial %}
{% load translate %}
{% load i18n %}
{% block meta %}{% endblock meta %}
{% block title %}{% trans 'لیست علاقه مندی‌ها' %}{% endblock title %}
{% block header %}{% endblock header %}
{% block main %}
<section>
    <div class="title">
        <h1>{% trans 'لیست علاقه مندی‌ها' %}</h1>
    </div>
    <div>
        {% if favorite_food_user %}
        <div class="title"><h2>{% trans 'غذاهای مورد علاقه' %}</h2></div>
        {% endif %}
        <div class="container">
        {% if favorite_food_user or favorite_blog_user %}
        {% for item in favorite_food_user %}
        <div class="container box-model-3 food-cart" style="text-align:right;width: 300px;height: 507px;margin:15px">
            <div class="text-center">
                <div>
                    <img src="{{media}}{{item.food.food_image}}" alt="">
                </div>
                <div><h3>{{item.food.food_name|translate}}</h3></div>
                <div><span>{% trans 'گارانتی اصالت و سلامت فیزیکی' %}</span></div>
                <div><span><i class="fa fa-clock-o"></i></span> <span>{% trans 'زمان پخت:' %}</span> <span>{{item.food.food_time}}</span> <span>{% trans 'دقیقه' %}</span></div>
                <div>
                {% if item.final_price < item.price %}
                    <del>{{item.price}}</del> <span>{% trans 'تومان' %}</span>
                    <p class="price">{{item.final_price}} <span>{% trans 'تومان' %}</span></p>
                {% else %}
                <p class="price">{{item.food.food_price}} <span>{% trans 'تومان' %}</span></p>
                {% endif %}
                </div>
                <div>
                    <div class="count-qty container">
                        <span class="btn btn-model-1 hover-m1" onclick="add_to_food_cart('{{item.food.id}}',1)"><i class="fa fa-cart-plus"></i></span>
                        {% if user.is_authenticated %}
                        {% if item.food.get_user_favorite %}
                        <a class="btn btn-model-1 hover-m1" onclick="delete_to_favorite('{{item.food.id}}')"><i class="fa fa-heart" style="color:black"></i></a>
                        {% else %}
                        <a class="btn btn-model-1 hover-m1" onclick="add_to_favorite('{{item.food.id}}')"><i class="fa fa-heart"></i></a>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-model-1 hover-m1" onclick="navigator.share({title:`{% trans 'اشتراک گذاری غذای' %} {{food.food_name|translate}} {% trans 'سایت فودینو' %}`,text:'{{food.food_description|translate}}','url':`{% url 'food_app:show_food' item.food.food_slug %}`})"><i class="fa fa-send"></i></a>
                    </div>
                </div>
                <div><a href="{% url 'food_app:show_food' item.food.food_slug %}" class="btn text-center" style="width: 97%;height: 35px;line-height: 35px;position: relative;top:18px;border-radius: 0 0 10px 10px;">{% trans 'مشاهده محصول' %}</a></div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if favorite_blog_user %}   
    <div class="title"><h2>{% trans 'مقاله‌ی مورد علاقه' %}</h2></div>
    {% endif %}
        <div class="container">
            {% for item in favorite_blog_user %}
            <div class="box-model-1">
                <div>
                    <div class="box-model-1-price">
                        <span>{{item.blog.article_register_date}}</span>
                    </div>
                    <div class="box-model-1-image">
                        <img src="{{media}}{{item.blog.article_main_image}}" type="image/jpg" alt="" class="food-image">
                    </div>
                </div>
                <div class="box-model-1-title">
                    <div><h3>{{item.blog.article_title|translate}}</h3></div>
                </div>
                <div class="box-model-1-buttons">
                    <div>
                        <a href="{{item.blog.id}}" class="btn btn-model-1"><i class="fa fa-save"></i></a>
                        {% if user.is_authenticated %}
                        {% if item.blog.get_user_favorite_blog %}
                        <a class="btn btn-model-1" title="حذف از علاقه‌مندی‌ها" onclick="delete_to_favorite_blog('{{item.blog.id}}')"><i class="fa fa-heart" style="color:black"></i></a>
                        {% else %}
                        <a class="btn btn-model-1" title="{% trans 'افزودن به علاقه‌مندی‌ها' %}" onclick="add_to_favorite_blog('{{item.blog.id}}')"><i class="fa fa-heart"></i></a>
                        {% endif %}
                        {% endif %}
                        <a class="btn btn-model-1" onclick="navigator.share({title:`{% trans 'اشتراک گذاری مقاله' %} {{blog.article_title|translate}} {% trans 'تارنما فودینو' %}`,text:'{{item.blog.article_summary_text|translate}}','url':`{% url 'blog_app:show_blog' item.blog.article_slug %}`})"><i class="fa fa-send"></i></a>
                    </div>
                    <div>
                        <a href="{% url 'blog_app:show_blog' item.blog.article_slug %}" class="btn btn-show-more">{% trans 'ادامه مطلب' %}</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <h2>
            {% trans 'محصولی را در این قسمت وارد نکردید.' %}
        </h2>
        {% endif %}
        </div>
    </div>
</section>
{% endblock main %}